# Site settings
title: Ocean Blog
email: dachang221@126.com
description: > # this means to ignore newlines until "baseurl:"
  User Interface Designer, iOS Developer, Unity3D Developer, 
  Master Candidate at College of Design & Innovation, Tongji University, 
  Shanghai, China.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: dachang
github_username:  dachang

# Build settings
markdown: kramdown
